---
- name: Add ArgoCD Helm repository
  kubernetes.core.helm_repository:
    kubeconfig: "{{ microk8s_kubeconfig }}"
    repo_name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Install ArgoCD
  kubernetes.core.helm:
    kubeconfig: "{{ microk8s_kubeconfig }}"
    chart_ref: argo/argo-cd
    chart_version: "{{ argocd_version }}"
    release_name: argocd
    release_namespace: argocd
    create_namespace: true
    update_repo_cache: true
    wait: true
    values: "{{ lookup('template', 'templates/argocd-helm-values.yml.j2') | from_yaml }}"

- name: Create HTTPS Certificate
  kubernetes.core.k8s:
    kubeconfig: "{{ microk8s_kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'files/argocd-server-https-cert.yml') | from_yaml_all }}"

- name: Create GRPC Certificate
  kubernetes.core.k8s:
    kubeconfig: "{{ microk8s_kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'files/argocd-server-grpc-cert.yml') | from_yaml_all }}"

- name: Create ArgoCD monitoring in Prometheus
  kubernetes.core.k8s:
    kubeconfig: "{{ microk8s_kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'files/argocd-alertmanager.rules.yml') | from_yaml_all }}"
  tags:
    - prometheus
