---
- name: Check Kubeconfig file
  ansible.builtin.stat:
    path: "{{ microk8s_kubeconfig }}"

- name: Add Jetstack Helm repository
  kubernetes.core.helm_repository:
    kubeconfig: "{{ microk8s_kubeconfig }}"
    repo_name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install Cert-Manager
  kubernetes.core.helm:
    kubeconfig: "{{ microk8s_kubeconfig }}"
    chart_ref: jetstack/cert-manager
    chart_version: "{{ cert_manager_version }}"
    release_name: cert-manager
    release_namespace: cert-manager
    create_namespace: true
    update_repo_cache: true
    wait: true
    values:
      installCRDs: true

- name: Create production ClusterIssuer
  kubernetes.core.k8s:
    kubeconfig: "{{ microk8s_kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'files/clusterissuer-prod.yml') | from_yaml_all }}"

- name: Create staging ClusterIssuer
  kubernetes.core.k8s:
    kubeconfig: "{{ microk8s_kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'files/clusterissuer-staging.yml') | from_yaml_all }}"
