---

- name: Install Python dependencies
  ansible.builtin.pip:
    name:
      - kubernetes>=29.0.0
      - jsonpatch
    state: present
    extra_args: "--system"
  tags: packages

- name: Include Microk8s server tasks
  ansible.builtin.include_tasks:
    file: microk8s.yml
    apply:
      tags:
        microk8s-server
  tags: microk8s-server

- name: Include Helm tasks
  ansible.builtin.include_tasks:
    file: helm.yml
    apply:
      tags:
        helm
  tags: helm

- name: Include Cert Manager tasks
  ansible.builtin.include_tasks:
    file: cert-manager.yml
    apply:
      tags:
        cert-manager
  tags: cert-manager

- name: Include CSI Driver NFS tasks
  ansible.builtin.include_tasks:
    file: csi-driver-nfs.yml
    apply:
      tags:
        nfs
  tags: nfs

- name: Include Prometheus tasks
  ansible.builtin.include_tasks:
    file: prometheus.yml
    apply:
      tags:
        prometheus
  tags: prometheus

- name: Include ArgoCD tasks
  ansible.builtin.include_tasks:
    file: argocd.yml
    apply:
      tags:
        argocd
  tags: argocd

- name: Include Vault tasks
  ansible.builtin.include_tasks:
    file: vault.yml
    apply:
      tags:
        vault
  tags: vault
