---
- name: Check Kubeconfig file
  ansible.builtin.stat:
    path: "{{ microk8s_kubeconfig }}"

- name: Add Prometheus Community Helm repository
  kubernetes.core.helm_repository:
    kubeconfig: "{{ microk8s_kubeconfig }}"
    repo_name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install Prometheus Community
  kubernetes.core.helm:
    kubeconfig: "{{ microk8s_kubeconfig }}"
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: "{{ kube_prometheus_stack_version }}"
    release_name: prom
    release_namespace: monitoring
    create_namespace: true
    update_repo_cache: true
    wait: true
    values: "{{ lookup('file', 'files/prometheus-helm-values.yml') | from_yaml }}"

- name: Create Grafana HTTPS Certificate
  kubernetes.core.k8s:
    kubeconfig: "{{ microk8s_kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'files/grafana-server-https-cert.yml') | from_yaml_all }}"
