kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hostpath
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /srv/hostpath
volumeBindingMode: WaitForFirstConsumer
