---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: monitoring
spec:
  # Secret names are always required.
  secretName: grafana-server-tls
  subject:
    organizations:
      - Farzad
  # At least one of a DNS Name, URI, IP address or otherName is required.
  dnsNames:
    - fargo-grafana.farzad.tech
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
