---
prometheus:
  service:
    type: NodePort

  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "hostpath"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - fargo-grafana.farzad.tech
    tls:
      - secretName: grafana-server-tls
        hosts:
          - fargo-grafana.farzad.tech
  persistence:
    enabled: true
    type: sts
    storageClassName: "hostpath"
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    finalizers:
      - kubernetes.io/pvc-protection
