version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "ansible"
    directory: "/ansible"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
    groups:
      ansible-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
    groups:
      terraform-dependencies:
        patterns:
          - "*"
