version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
