---

#- name: Add APT keys
#  apt_key: keyserver={{ item.keyserver }} id={{ item.id }} state={{ item.state | default("present") }}
#  loop: "{{ global.apt_keys }}"
#  tags: configuration

# For Let's Encrypt
#- name: Setup Debian repositories
#  apt_repository:
#    repo: "{{ item.repo }}"
#    state: "{{ item.state | default('present') }}"
#    filename: "{{ item.filename }}"
#  loop: "{{ global.apt_repositories }}"
#  tags: configuration

- ansible.builtin.include_tasks:
    file: debian.yml
    apply:
      tags:
        - debian
  tags:
    - debian

#- name: Install Git config
#  template: src=gitconfig.j2 dest={{ me.home }}/.gitconfig mode="0600" owner=farzy group=farzy
#  tags: configuration

- ansible.builtin.include_tasks:
    file: zsh.yml
    apply:
      tags:
        - zsh
  tags:
    - zsh

- ansible.builtin.include_tasks:
    file: user-config.yml
    apply:
      tags:
        - configuration
  tags:
    - configuration

#- name: Install Dropbox
#  become: yes
#  become_user: farzy
#  shell: cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
#  args:
#    creates: "{{ me.home }}/.dropbox-dist"
#  tags: packages
#
#- name: Sysctl settings for Dropbox
#  sysctl: name="fs.inotify.max_user_watches" value=100000 sysctl_set=yes state=present reload=yes
#
#- name: Unit file for Dropbox
#  template: src="dropbox-farzy.service.j2" dest="/lib/systemd/system/dropbox-farzy.service" mode="0644" owner=root group=root
##  notify: Reload systemd
#
#- name: Activate Dropbox Unit
#  service: name="dropbox-farzy" enabled=yes state=started
