---

- name: Install personal config files for root
  ansible.builtin.template:
    src: "dotfiles/{{ item.name }}"
    dest: "/root/{{ item.name }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: root
    group: root
  loop: "{{ user_dotfiles }}"
  tags: configuration

- name: Install personal config files for main user
  ansible.builtin.template:
    src: "dotfiles/{{ item.name }}"
    dest: "{{ user_home }}/{{ item.name }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ user_owner }}"
    group: "{{ user_group }}"
  loop: "{{ user_dotfiles }}"
  tags: configuration
