---
farzy:
  name: "Farzad FARID"
  email:
    personal: "farzy@farzy.org"
    pro: "ffarid@pragmatic-source.com"
  home: "/data/home/farzy"
  dotfiles:
    - name: ".gitignore_global"
    - name: ".bashrc"
    - name: ".profile"
    - name: ".tmux.conf"
    #- name: ".config"

global:
  etcfiles:
    - name: "profile.d"
      mode: "0644"
    - name: "vim"
      mode: "0644"
    - name: "screenrc"
      mode: "0644"
  debconf:
    - name: debconf
      question: priority
      value: low
      vtype: select
    - name: postfix
      question: mailname
      value: "pragmatic-source.com"
      vtype: string
  packages:
    - aptitude
    - apt-listchanges
    - apt-listbugs
    - apt-rdepends
    - apt-show-source
    - apt-show-versions
    - apt-utils
    - build-essential
    - bzip2
    - debconf
    - deborphan
    - debsums
    - devscripts
    - dh-make
    - dlocate
    - dmidecode
    - dnsutils
    - fakeroot
    - git
    - gnupg
    - haskell-platform
    - htop
    - iftop
    - less
    - lftp
    - logrotate
    - lsof
    - ltrace
    - lynx
    - mlocate
    - mmv
    - mtr
    - mutt
    - ncdu
    - nmap
    - powerline
    - pure-ftpd
    - python-pip
    - reportbug
    - rsync
    - strace
    - sudo
    - tcpdump
    - traceroute
    - tshark
    - unzip
    - wdiff
    - wget
    - whois
    - zip

packages_with_config:
  - awscli
  - cron-apt
  - postfix
  - screen
  - tmux
  - vim
  - vim-addon-manager
  - zsh
