---
name: Molecule CI/CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-22.04
    env:
      NGINX_CRT: ${{ secrets.NGINX_CRT }}
      NGINX_KEY: ${{ secrets.NGINX_KEY }}
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          - distribution
          - downgrade
          - downgrade-plus
          - plus
          - source
          - stable
          - uninstall
          - uninstall-plus
          - upgrade
          - upgrade-plus
          - version
    steps:
      - name: Check out the codebase
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        uses: actions/checkout@v3

      - name: Set up Docker QEMU
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: aarch64,s390x

      - name: Set up Python 3
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Molecule dependencies
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        run: pip3 install -r .github/workflows/requirements/requirements_molecule.txt

      - name: Install Ansible core dependencies
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        run: ansible-galaxy install -r .github/workflows/requirements/requirements_ansible.yml

      - name: Run Molecule tests
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
