---

- name: Install packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - kubernetes-cli

- name: Install personal config files
  template:
    src: "dotfiles/{{ item }}"
    dest: "~/{{ item }}"
  loop:
    - .zshrc
  tags: configuration
