---

- name: Install packages
  homebrew:
    name:
      - awscli
      - bat
      - colordiff
      - coreutils
      - direnv
      - fd
      - gnu-sed
      - gnupg
      - golang
      - htop
      - htop
      - htop-osx
      - hugo
      - ipcalc
      - jq
      - kube-ps1
      - kubernetes-cli
      - kubernetes-helm
      - mmv
      - ncdu
      - ncdu
      - nmap
      - node
      - nvm
      - p7zip
      - pipenv
      - pwgen
      - python@3.9
      - ripgrep
      - rustup
      - terraform@0.12
      - vault
      - watch
      - yq
    state: present
  tags:
    - packages

- name: List installed Heml plugins
  shell:
    cmd: "helm plugin list | tail -n +2 | cut -f 1"
  register: helm_plugins
  check_mode: false
  changed_when: false
  tags:
    - packages
    - helm

- name: Install Helm plugins
  shell:
    cmd: "helm plugin install {{ item.url }} || helm plugin update {{ item.name }}"
  loop:
    - url: https://github.com/hypnoglow/helm-s3.git
      name: s3
  when: item.name not in helm_plugins.stdout
  tags:
    - packages
    - helm

- name: Test the installation of Oh My Zsh
  stat:
    path: "{{ oh_my_zsh_home }}"
  register: stat_omz
  check_mode: false
  tags:
    - configuration
    - zsh

- name: Download the Oh My Zsh installer
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/omz-installer.sh
    mode: '0755'
  when: stat_omz.stat.exists == False
  tags:
    - configuration
    - zsh

- name: Install Oh My Zsh
  shell:
    cmd: "/tmp/omz-installer.sh"
    chdir: /tmp
  when: stat_omz.stat.exists == False
  tags:
    - configuration
    - zsh

- name: Install OMZ theme Powerlevel10k
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    version: "master"
    dest: "{{ oh_my_zsh_home }}/custom/themes/powerlevel10k"
    accept_hostkey: yes
  tags:
    - configuration
    - zsh

- name: Install ZSH Autosuggestions plugin
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    version: "master"
    dest: "{{ oh_my_zsh_home }}/custom/plugins/zsh-autosuggestions"
    accept_hostkey: yes
  tags:
    - configuration
    - zsh

- name: Fix some permissions
  file:
    path: '{{ item }}'
    mode: '755'
    state: directory
    recurse: false
  loop:
    - /usr/local/share
    - /usr/local/share/zsh
    - /usr/local/share/zsh/site-functions
  tags:
    - configuration
    - zsh

# Change Ansible/Jinja block delimiters in order to avoid issues with shell
# syntax '${%…}'.
- name: Install personal config files
  template:
    src: "dotfiles/{{ item }}"
    dest: "~/{{ item }}"
    block_start_string: "{|"
    block_end_string: "|}"
  loop:
    - .zshrc
    - .p10k.zsh
  tags:
    - configuration
    - zsh
