---

- name: Install packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - pyenv-virtualenv
    - pyenv-virtualenvwrapper

- name: Install personal config files
  template: src="dotfiles/{{ item.key }}" dest="{{ me.home }}/{{ item.value.name }}" mode={{ item.value.mode | default("0644") }} owner={{ me.user }} group={{ me.group }}
  with_dict: "{{ me.dotfiles }}"
  tags: configuration
