---

- name: Install packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - golang
    - rustup
    #- kubernetes-cli
    #- awscli
    - coreutils
    - htop
    - direnv
    - kubernetes-helm
    - jq
    - kops
    - p7zip
    - ripgrep
    - bat
    - fd
    - ncdu


# TODO: helm plugin install https://github.com/hypnoglow/helm-s3.git

- name: Test the installation of Oh My Zsh
  stat:
    path: "{{ oh_my_zsh_home }}"
  register: stat_omz
  check_mode: false

- name: Download the Oh My Zsh installer
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/omz-installer.sh
    mode: '0755'
  when: stat_omz.stat.exists == False

- name: Install Oh My Zsh
  shell:
    cmd: "/tmp/omz-installer.sh"
    chdir: /tmp
  when: stat_omz.stat.exists == False

- name: Install OMZ theme Powerlevel10k
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    version: "master"
    dest: "{{ oh_my_zsh_home }}/custom/themes/powerlevel10k"
    accept_hostkey: yes

- name: Install ZSH Autosuggestions plugin
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    version: "master"
    dest: "{{ oh_my_zsh_home }}/custom/plugins/zsh-autosuggestions"
    accept_hostkey: yes

# Change Ansible/Jinja block delimiters in order to avoid issues with shell
# syntax '${%…}'.
- name: Install personal config files
  template:
    src: "dotfiles/{{ item }}"
    dest: "~/{{ item }}"
    block_start_string: "{|"
    block_end_string: "|}"
  loop:
    - .zshrc
    - .p10k.zsh
  tags: configuration
