---
# XXX Fix this for Ansible 9.3
- name: Remove Brew packages
  community.general.homebrew:
    name: "{{ homebrew_packages_removed }}"
    state: absent
  tags:
    - packages
  ignore_errors: true

- name: Install Brew packages
  community.general.homebrew:
    name: "{{ homebrew_packages | reject('equalto', omit) | list }}"
    update_homebrew: true
    state: present
  tags:
    - packages
