---

- name: "Install Linux server"
  hosts: linux_servers

  roles:
    - role: master_setup
      tags: deploy
    - role: iterm2_integration
      tags: iterm2
  vars:
    iterm2_integration_users:
      - { name: "root", home_path: "/root", owner: "root", group: "root" }
      - { name: "debian", home_path: "/home/debian", owner: "debian", group: "debian" }
