---
- name: Deploy OpenClaw
  hosts: openclaw
  become: true
  vars_files:
    - ../vars/openclaw.yml
  roles:
    - role: master_setup
      tags: setup
    - role: fastmail_mcp_setup
      tags: fastmail_mcp
    - role: openclaw_setup
      tags: openclaw
