---

- hosts: web

  name: "Install server"
  collections:
    - nginxinc.nginx_core
  roles:
    - role: master-setup
      tags: deploy
  tasks:
    - name: Install NGINX
      ansible.builtin.include_role:
        name: nginx
        apply:
          tags:
            nginx
      tags: nginx
    - name: Prepare web directory
      file:
        path: /srv/www/farzy.org
        state: directory
        owner: www-data
        group: adm
        mode: 02775
      tags: www
  vars_files:
    - ../vars/web.yml

- hosts: localhost
  name: Install web content
  vars_files:
    - ../vars/web.yml
  tasks:
    - name: Install personal web site with Hugo
      shell:
        cmd: ./deploy
        chdir: "{{ hugo_home }}"
      tags: www
