---

- hosts: web

  name: "Install server"
  roles:
    - role: master-setup
      tags: deploy
    - role: nginxinc.nginx
      tags: nginx
  tasks:
    - name: Prepare web directory
      file:
        path: /srv/www/farzy.org
        state: directory
        owner: www-data
        group: adm
        mode: 02775
      tags: www
  vars_files:
    - ../vars/web.yml

- hosts: localhost
  name: Install web content
  vars_files:
    - ../vars/web.yml
  tasks:
    - name: Install personal web site with Hugo
      shell:
        cmd: ./deploy
        chdir: "{{ hugo_home }}"
      tags: www
