---

global:
  etcfiles:
    - name: "profile.d"
      mode: "0644"
    - name: "vim"
      mode: "0644"
    - name: "screenrc"
      mode: "0644"
  apt_repositories:
    - repo: 'deb http://ftp.debian.org/debian jessie-backports main contrib non-free'
      state: present
      filename: 'jessie-backports'
    - repo: "deb [arch=amd64,i386] http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.1/debian jessie main"
      filename: "mariadb"
  apt_keys:
    - keyserver: "hkp://keyserver.ubuntu.com:80"
      id: "0xcbcb082a1bb943db"
  debconf:
    - name: debconf
      question: "debconf/priority"
      value: low
      vtype: select
    - name: postfix
      question: "postfix/mailname"
      value: "farzy.org"
      vtype: string
  packages:
#    - aptitude
#    - apt-listchanges
#    - apt-listbugs
#    - apt-rdepends
#    - apt-show-source
#    - apt-show-versions
#    - apt-utils
    - bash-completion
#    - build-essential
    - bzip2
#    - cronolog
    - debconf
    - deborphan
#    - debsums
#    - devscripts
#    - dh-make
    - dlocate
#    - dmidecode
    - dnsutils
#    - fakeroot
    - git
#    - gnupg
    - htop
#    - iftop
    - less
#    - lftp
#    - logrotate
    - lsof
    - ltrace
    - mlocate
    - mmv
    - mtr
#    - mutt
    - ncdu
    - nmap
    - rsync
    - screen
    - strace
    - tcpdump
    - tmux
    - traceroute
    - tshark
    - unzip
    - vim
    - wdiff
#    - wget
    - whois
    - zip
    - zsh
