---

is_debian_lower_12: "{{ ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] | int < 12 }}"

global_etcfiles:
  - name: "profile.d/pragmatic.sh"
    mode: "0644"
  - name: "vim/vimrc"
    mode: "0644"
  - name: "screenrc"
    mode: "0644"
  - name: "apt/apt.conf.d/50unattended-upgrades"
    mode: "0644"
global_apt_repositories:
  - repo: 'deb http://ftp.debian.org/debian jessie-backports main contrib non-free'
    state: present
    filename: 'jessie-backports'
  - repo: "deb [arch=amd64,i386] http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.1/debian jessie main"
    filename: "mariadb"
global_apt_keys:
  - keyserver: "hkp://keyserver.ubuntu.com:80"
    id: "0xcbcb082a1bb943db"
global_debconf_defaults:
  - name: debconf
    question: "debconf/priority"
    value: low
    vtype: select
  - name: debconf
    question: debconf/frontend
    value: Noninteractive
    vtype: select
  - name: postfix
    question: "postfix/mailname"
    value: "farzy.org"
    vtype: string
  - name: locales
    question: locales/default_environment_locale
    value: en_US.UTF-8
    vtype: select
  - name: locales
    question: locales/locales_to_be_generated
    value: "en_US.UTF-8 UTF-8"
    vtype: multiselect
global_packages_apt:
#      - aptitude
#      - apt-listchanges
#      - apt-listbugs
#      - apt-rdepends
#      - apt-show-source
#      - apt-show-versions
#      - apt-utils
  - bash-completion
  - bat
#      - build-essential
  - bzip2
#      - cronolog
  - debconf
  - deborphan
#      - debsums
#      - devscripts
#      - dh-make
  - dlocate
#      - dmidecode
  - dnsutils
  - elinks
#      - fakeroot
  - git
#      - gnupg
  - jq
  - htop
#      - iftop
  - less
#      - lftp
  - locales
#      - logrotate
  - lsof
  - ltrace
  - mlocate
  - mmv
  - mtr
#      - mutt
  - ncdu
  - nmap
  - python3-pip
  - rsync
  - screen
  - strace
  - tcpdump
  - tmux
  - traceroute
  - tshark
  - unattended-upgrades
  - unzip
  - vim
  - wdiff
#      - wget
  - whois
  - "{{ 'yq' if not is_debian_lower_12 else omit}}"
  - zip
  - zsh
# Only for Debian < 12
global_packages_pip_system:
  - yq

user_home: /home/debian
user_owner: debian
user_group: debian
user_dotfiles:
  - name: .bashrc
  - name: .gitignore_global
  - name: .profile
  - name: .zshrc

install_microk8s: false
