---
- name: Install packages
  ansible.builtin.include_tasks:
    file: packages.yml
    apply:
      tags:
        packages
  tags: packages

- name: Configure SSH
  ansible.builtin.include_tasks:
    file: ssh.yml
    apply:
      tags:
        ssh
  tags: ssh

- name: List installed Helm plugins
  shell:
    cmd: "helm plugin list | tail -n +2 | cut -f 1"
  register: helm_plugins
  check_mode: false
  changed_when: false
  tags:
    - packages
    - helm

- name: Install Helm plugins
  shell:
    cmd: "helm plugin install {{ item.url }} || helm plugin update {{ item.name }}"
  loop:
    - url: https://github.com/hypnoglow/helm-s3.git
      name: s3
  when: item.name not in helm_plugins.stdout
  tags:
    - packages
    - helm

- name: Install Oh My Zsh and configure ZSH
  ansible.builtin.include_tasks:
    file: zsh.yml
    apply:
      tags:
        zsh
  tags: zsh

# Change Ansible/Jinja block delimiters in order to avoid issues with shell
# syntax '${%…}'.
- name: Install personal config files
  template:
    src: "dotfiles/{{ item }}"
    dest: "~/{{ item }}"
    block_start_string: "{|"
    block_end_string: "|}"
  loop:
    - .gitconfig
    - .gitconfig-personal
    - .gitconfig-professional
    - .gitignore_global
    - .p10k.zsh
    - .tmux.conf
    - .zshrc
  tags:
    - configuration
    - zsh

- name: Create iTerm2 DynamicProfiles
  template:
    src: "iTerm2/personal.json.j2"
    dest: "{{ iterm2_library_path }}/DynamicProfiles/personal.json"
  tags:
    - configuration
    - iterm2
