---
# XXX Fix this for Ansible 9.3
- name: Remove Brew packages
  community.general.homebrew:
    name: "{{ homebrew_packages_removed }}"
    state: absent
  tags:
    - packages
  ignore_errors: true
  when: is_macos

- name: Install Brew packages
  community.general.homebrew:
    name: "{{ homebrew_packages | reject('equalto', omit) | list }}"
    update_homebrew: true
    state: present
  tags:
    - packages
  when: is_macos

- name: Install Debian / Ubuntu packages
  ansible.builtin.apt:
    name: "{{ global_packages_apt | reject('equalto', omit) | list }}"
    state: present
  become: true
  become_user: root
  tags: packages
  when: is_debian_family
