---
- name: Install SSH certificates
  ansible.builtin.copy:
    src: "ssh/{{ item }}"
    dest: "~/.ssh/{{ item }}"
    mode: "0600"
  loop:
    - azure-farzad.pem
    - ca_host_key
    - ca_host_key.pub
    - ca_user_key
    - ca_user_key.pub
    - id_ed25519
    - id_ed25519.pub

- name: "Install SSH config files"
  ansible.builtin.template:
    src: "ssh/config"
    dest: "~/.ssh/config"
    mode: "0600"
