---

- name: Create Farzad's group
  group:
    name: farzy
    gid: 1000
    state: present

- name: Create Farzad's user
  user:
    name: farzy
    uid: 1000
    state: present
    append: yes
    comment: Farzad FARID
    group: farzy
    groups: "sudo,adm"
    shell: /bin/bash
    password: "{{ passwords.farzy }}"

- name: Set up authorized_keys for farzy
  authorized_key:
    user: farzy
    exclusive: yes
    manage_dir: yes
    key: "{{ item }}"
  with_file:
    - files/ssh-pubkey-farzy

- name: Set up authorized_keys for root
  authorized_key:
    user: root
    exclusive: yes
    manage_dir: yes
    key: "{{ item }}"
  with_file:
    - files/ssh-pubkey-farzy

- name: Setup Debian packages configuration (debconf)
  debconf: name="{{ item.name }}" question="{{ item.question }}" value="{{ item.value }}" vtype="{{ item.vtype }}"
  with_items: "{{ global.debconf }}"
  tags: configuration

- name: Install packages
  apt: name={{ item }} state=present
  with_items: "{{ global.packages }}"
  tags: packages

- name: Install Powerline Gitstatus
  pip: name="powerline-gitstatus" state=latest

- name: Install global /etc files
  copy: src="etcfiles/{{ item.name }}" dest="/etc/" mode={{ item.mode | default("0644") }} owner=root group=root
  with_items: "{{ global.etcfiles }}"
  tags: configuration


- name: Install Git config
  template: src=gitconfig.j2 dest={{ farzy.home }}/.gitconfig mode="0600" owner=farzy group=farzy
  tags: configuration

- name: Install personal config files
  copy: src="dotfiles/{{ item.name }}" dest="{{ farzy.home }}/" mode={{ item.mode | default("0644") }} owner=farzy group=farzy
  with_items: "{{ farzy.dotfiles }}"
  tags: configuration

- name: Install Dropbox
  become: yes
  become_user: farzy
  shell: cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf - creates="{{ farzy.home }}/.dropbox-dist"
  tags: packages

- name: Sysctl settings for Dropbox
  sysctl: name="fs.inotify.max_user_watches" value=100000 sysctl_set=yes state=present reload=yes

- name: Unit file for Dropbox
  template: src="dropbox-farzy.service.j2" dest="/lib/systemd/system/dropbox-farzy.service" mode="0644" owner=root group=root
#  notify: Reload systemd

- name: Activate Dropbox Unit
  service: name="dropbox-farzy" enabled=yes state=started
